### ISSUE TITLE
Event is not defined

### ISSUE THREAD

**Issue by naeemijaz** [johnvsnagendra/solana-nft-minter#1]
ReferenceError: Event is not defined
    at file:///C:/xampp/htdocs/ItSolzTechOkara/solana-nft-minter/node_modules/@wallet-standard/wallet/lib/esm/register.js:44:35
    at ModuleJob.run (internal/modules/esm/module_job.js:170:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24) {
  page: '/'
}

**Comment by JohnVersus** [comment]
Hi @naeemijaz, Can you provide more details for reproducing the error?
